const COLOR_PRIMARY = '#0FB2BC';
const COLOR_PRIMARY_LIGHT = '#A6DFE2';
const COLOR_BACKGROUND = '#E8EDEF';
const COLOR_TEXT_LIGHT = '#B8B9BA';
const COLOR_BACKGROUND_DARK = '#7A7676';
const COLOR_BACKGROUND_LIGHT = '#F7F7F7';

export {
  COLOR_PRIMARY,
  COLOR_PRIMARY_LIGHT,
  COLOR_BACKGROUND,
  COLOR_TEXT_LIGHT,
  COLOR_BACKGROUND_DARK,
  COLOR_BACKGROUND_LIGHT,
};
